--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/RevandDev/BuyHealFeed
build-by-default: true
branches:
- main
projects:
  BuyHealFeed:
    path: ""
    icon: "icon/icon.png"
    libs:
      - src: cooldogedev/libSQL/libSQL
        version: ^0.1.0
...
