name: BuyHealFeed
main: Rev\BuyHealFeed\Main
version: 1.1
api: [4.0.0]
depend: ["BedrockEconomy"]
author: Revand

permissions:
  buyhealfeed.cmd:
    default: true
    description: BuyHealFeed Cmd Permision

commands:
  buyheal:
    description: BuyHeal
    permission: buyhealfeed.cmd
  buyfeed:
    description: BuyFeed
    permission: buyhealfeed.cmd
